version: "3.5"

services:
  database:
    container_name: database
    image: mariadb
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - "3306:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=rootPassword
       - MYSQL_DATABASE=laravel
       - MYSQL_USER=dbUser
       - MYSQL_PASSWORD=dbPassword
    volumes:
      - db-data-volume:/var/lib/mysql

volumes:
  db-data-volume: